// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.UInt32 clientID;
            [FieldOffset(4)]
            public Vector3 newPosition;
        }

        public static unsafe _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 16) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 16) " +
                    "for command with ID 7");
            }

            var orig = new _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f();
            var comp = (Interop*)data;
            orig.clientID = comp->clientID;
            orig.newPosition = comp->newPosition;
            return orig;
        }

        public System.UInt32 clientID;
        public Vector3 newPosition;
        
        public Entity Entity { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 7;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f(
        Entity entity,
        System.UInt32 clientID,
        Vector3 newPosition
)
        {
            Entity = entity;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.clientID = clientID; 
            this.newPosition = newPosition; 
        }
        
        public static void Serialize(_47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteUIntegerRange(commandData.clientID, 32, 0);
            var converted_newPosition = commandData.newPosition.ToCoreVector3();
            bitStream.WriteVector3(converted_newPosition, FloatMeta.NoCompression());
        }
        
        public static _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var dataclientID = bitStream.ReadUIntegerRange(32, 0);
            var converted_newPosition = bitStream.ReadVector3(FloatMeta.NoCompression());
            var datanewPosition = converted_newPosition.ToUnityVector3();
    
            return new _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f()
            {
                Entity = entity,
                Routing = target,
                clientID = dataclientID,
                newPosition = datanewPosition
            };   
        }
    }

}