// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;

    public struct _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Vector4 color;
            [FieldOffset(16)]
            public System.UInt32 clientId;
        }

        public static unsafe _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 20) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 20) " +
                    "for component with ID 154");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 154");
            }

            var orig = new _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110();

            var comp = (Interop*)data;

            orig.color = comp->color;
            orig.clientId = comp->clientId;

            return orig;
        }


        public static uint colorMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame colorSimulationFrame;
        public Color color;
        public static uint clientIdMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame clientIdSimulationFrame;
        public System.UInt32 clientId;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 154;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000011;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 2;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;

        private static readonly System.UInt32 _clientId_Min = 0;
        private static readonly System.UInt32 _clientId_Max = 4294967295;

        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_66694146d0cbe4600b7e26ae35719cfa_7769962969807975110)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.colorSimulationFrame = other.colorSimulationFrame;
                this.color = other.color;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.clientIdSimulationFrame = other.clientIdSimulationFrame;
                this.clientId = other.clientId;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_66694146d0cbe4600b7e26ae35719cfa_7769962969807975110 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 2);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = (data.color.ToCoreColor());



                bitStream.WriteColor(fieldValue, FloatMeta.ForFixedPoint(0, 1, 2.3283064370808E-10d));
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {

                Coherence.Utils.Bounds.Check(data.clientId, _clientId_Min, _clientId_Max, "_66694146d0cbe4600b7e26ae35719cfa_7769962969807975110.clientId", logger);

                data.clientId = Coherence.Utils.Bounds.Clamp(data.clientId, _clientId_Min, _clientId_Max);

                var fieldValue = data.clientId;



                bitStream.WriteUIntegerRange(fieldValue, 32, 0);
            }

            mask >>= 1;

            return mask;
        }

        public static _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(2);
            }

            var val = new _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110();
            if (bitStream.ReadMask())
            {

                val.color = bitStream.ReadColor(FloatMeta.ForFixedPoint(0, 1, 2.3283064370808E-10d)).ToUnityColor();
                val.FieldsMask |= _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110.colorMask;
            }
            if (bitStream.ReadMask())
            {

                val.clientId = bitStream.ReadUIntegerRange(32, 0);
                val.FieldsMask |= _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110.clientIdMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_66694146d0cbe4600b7e26ae35719cfa_7769962969807975110(" +
                $" color: { this.color }" +
                $" clientId: { this.clientId }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(2, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(2, '0') })";
        }
    }


}