// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;

    public struct _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Vector4 color;
            [FieldOffset(16)]
            public System.UInt32 clientId;
            [FieldOffset(20)]
            public Entity targetInteractable;
        }

        public static unsafe _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 24) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 24) " +
                    "for component with ID 154");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 154");
            }

            var orig = new _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110();

            var comp = (Interop*)data;

            orig.color = comp->color;
            orig.clientId = comp->clientId;
            orig.targetInteractable = comp->targetInteractable;

            return orig;
        }


        public static uint colorMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame colorSimulationFrame;
        public Color color;
        public static uint clientIdMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame clientIdSimulationFrame;
        public System.UInt32 clientId;
        public static uint targetInteractableMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame targetInteractableSimulationFrame;
        public Entity targetInteractable;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 154;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000111;
        public bool HasFields() => true;
        public bool HasRefFields() => true;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 3;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return new HashSet<Entity>()
            {
                this.targetInteractable,
            };
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            uint refsMask = 0;

            if (this.targetInteractable == fromEntity)
            {
                this.targetInteractable = toEntity;
                refsMask |= 1 << 2;
            }

            FieldsMask |= refsMask;

            return refsMask;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            Entity absoluteEntity;
            IEntityMapper.Error err;
            err = mapper.MapToAbsoluteEntity(this.targetInteractable, false, out absoluteEntity);

            if (err != IEntityMapper.Error.None)
            {
                return err;
            }

            this.targetInteractable = absoluteEntity;
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            Entity relativeEntity;
            IEntityMapper.Error err;
            // We assume that the inConnection held changes with unresolved references, so the 'createMapping=true' is
            // there only because there's a chance that the parent creation change will be processed after this one
            // meaning there's no mapping for the parent yet. This wouldn't be necessary if mapping creation would happen
            // in the clientWorld via create/destroy requests while here we would only check whether mapping exists or not.
            var createParentMapping_targetInteractable = true;
            err = mapper.MapToRelativeEntity(this.targetInteractable, createParentMapping_targetInteractable,
             out relativeEntity);

            if (err != IEntityMapper.Error.None)
            {
                return err;
            }

            this.targetInteractable = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;

        private static readonly System.UInt32 _clientId_Min = 0;
        private static readonly System.UInt32 _clientId_Max = 4294967295;

        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_66694146d0cbe4600b7e26ae35719cfa_7769962969807975110)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.colorSimulationFrame = other.colorSimulationFrame;
                this.color = other.color;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.clientIdSimulationFrame = other.clientIdSimulationFrame;
                this.clientId = other.clientId;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.targetInteractableSimulationFrame = other.targetInteractableSimulationFrame;
                this.targetInteractable = other.targetInteractable;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_66694146d0cbe4600b7e26ae35719cfa_7769962969807975110 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 3);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = (data.color.ToCoreColor());



                bitStream.WriteColor(fieldValue, FloatMeta.ForFixedPoint(0, 1, 2.3283064370808E-10d));
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {

                Coherence.Utils.Bounds.Check(data.clientId, _clientId_Min, _clientId_Max, "_66694146d0cbe4600b7e26ae35719cfa_7769962969807975110.clientId", logger);

                data.clientId = Coherence.Utils.Bounds.Clamp(data.clientId, _clientId_Min, _clientId_Max);

                var fieldValue = data.clientId;



                bitStream.WriteUIntegerRange(fieldValue, 32, 0);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = data.targetInteractable;



                bitStream.WriteEntity(fieldValue);
            }

            mask >>= 1;

            return mask;
        }

        public static _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(3);
            }

            var val = new _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110();
            if (bitStream.ReadMask())
            {

                val.color = bitStream.ReadColor(FloatMeta.ForFixedPoint(0, 1, 2.3283064370808E-10d)).ToUnityColor();
                val.FieldsMask |= _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110.colorMask;
            }
            if (bitStream.ReadMask())
            {

                val.clientId = bitStream.ReadUIntegerRange(32, 0);
                val.FieldsMask |= _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110.clientIdMask;
            }
            if (bitStream.ReadMask())
            {

                val.targetInteractable = bitStream.ReadEntity();
                val.FieldsMask |= _66694146d0cbe4600b7e26ae35719cfa_7769962969807975110.targetInteractableMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_66694146d0cbe4600b7e26ae35719cfa_7769962969807975110(" +
                $" color: { this.color }" +
                $" clientId: { this.clientId }" +
                $" targetInteractable: { this.targetInteractable }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(3, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(3, '0') })";
        }
    }


}