// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_47361547313d541f3ac181c817c5c727_1bf1488a4ff1445299a2482db16b708a : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_47361547313d541f3ac181c817c5c727 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_47361547313d541f3ac181c817c5c727>();
        
        private global::Simulator _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["1bf1488a4ff1445299a2482db16b708a"] = new Binding_47361547313d541f3ac181c817c5c727_1bf1488a4ff1445299a2482db16b708a(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_47361547313d541f3ac181c817c5c727()
        {
            bakedCommandBindings.Add("7ebcb117403b44f183ab55b12816462f", BakeCommandBinding__47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f_CommandTarget = (global::Simulator)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Simulator.MoveCharacterTo", "(System.UInt32UnityEngine.Vector3)", SendCommand__47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f, ReceiveLocalCommand__47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f, MessageTarget.All, _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f_CommandTarget, false);
        }
        
        private void SendCommand__47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f(MessageTarget target, object[] args)
        {
            var command = new _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f();
            
            int i = 0;
            command.clientID = (System.UInt32)args[i++];
            command.newPosition = (UnityEngine.Vector3)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f(MessageTarget target, object[] args)
        {
            var command = new _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f();
            
            int i = 0;
            command.clientID = (System.UInt32)args[i++];
            command.newPosition = (UnityEngine.Vector3)args[i++];
            
            ReceiveCommand__47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f(command);
        }

        private void ReceiveCommand__47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f(_47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f command)
        {
            var target = _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f_CommandTarget;
            
            target.MoveCharacterTo((System.UInt32)(command.clientID),(UnityEngine.Vector3)(command.newPosition));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f castedCommand:
                    ReceiveCommand__47361547313d541f3ac181c817c5c727_7ebcb117403b44f183ab55b12816462f(castedCommand);
                    break;
                default:
                    logger.Warning($"CoherenceSync_47361547313d541f3ac181c817c5c727 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_47361547313d541f3ac181c817c5c727>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}